services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miracletree-app
    restart: unless-stopped
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
