services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: miracletree-app
    restart: unless-stopped
    ports:
      - "127.0.0.1:3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=mongodb://mongodb:27017/miracletree
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:7.0.14
    container_name: miracletree-mongo
    restart: unless-stopped
    volumes:
      - miracletree_mongo_data:/data/db

  redis:
    image: redis:alpine
    container_name: miracletree-redis
    restart: unless-stopped

volumes:
  miracletree_mongo_data:
